apiVersion: v1
kind: Pod
metadata:
  name: ansible
spec:
  containers:
    - name: ansible
      image: <your-dockerhub-username>/jenkins-ansible:v1
      command: ["/bin/bash", "-c", "sleep infinity"]
