---
- name: Install Apache on Kubernetes nodes
  hosts: workers
  become: true
  tasks:
    - name: Install Apache
      package:
        name: httpd
        state: present

    - name: Start Apache
      service:
        name: httpd
        state: started
        enabled: yes
